version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - 80:8080   # Listen to HTTP on host port 80 and forward to keycloak on 8080
      - 443:8443  # Listen to HTTPS on host port 443 and forward to keycloak on 8443
    volumes:
      - "./certs/server.crt.pem:/etc/x509/https/tls.crt"   # Map certificate to container
      - "./certs/server.key.pem:/etc/x509/https/tls.key"   # Map private key to container
    environment:
      - KEYCLOAK_ADMIN_USER=admin        # Change the username!
      - KEYCLOAK_ADMIN_PASSWORD=admin # Change the password!
      - KEYCLOAK_ADMIN=admin
      - KC_HOSTNAME=fqdn                 # Set the hostname here
      - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key
    command:
      - start-dev # Start Keycloak in developer mode
